# group: !include groups.yaml
automation: !include automations.yaml
# script: !include scripts.yaml
# scene: !include scenes.yaml
sensor: !include sensor.yaml

alexa:
  smart_home:
    locale: en-GB
    endpoint: "https://api.eu.amazonalexa.com/v3/events"
    client_id: !secret alexa_client
    client_secret: !secret alexa_secret
    filter:
      exclude_entities:
        - binary_sensor.updater
        - switch.bedroom_wall_light
        - sensor.mobile_skynet_battery_temperature
        - sensor.mobile_skynet_battery_temperature

calendar:
  - platform: todoist
    token: !secret TODOIST

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

device_tracker:
  - platform: arris_tg2492lg
    host: 192.168.0.1
    password: !secret router_password
    # interval_seconds: 10
    # consider_home: 180
    new_device_defaults:
      track_new_devices: false

frontend:
  themes: !include_dir_merge_named themes

google:
  client_id: !secret GOOGLE_ID
  client_secret: !secret GOOGLE_SECRET
#   track_new_calendar: false

google_assistant:
  project_id: jarvis-b89c8
  service_account: !include SERVICE_ACCOUNT.JSON
  report_state: true
  entity_config:
    binary_sensor.updator:
      expose: false
    media_player.living_room_speaker:
      expose: false
    switch.bedroom_wall_light:
      expose: false
    sensor.mobile_skynet_battery_temperature:
      expose: false
    sensor.mobile_skynet_battery_temperature:
      expose: false

http:
  # For extra security set this to only accept connections on localhost if NGINX is on the same machine
  # Uncommenting this will mean that you can only reach Home Assistant using the proxy, not directly via IP from other clients.
  # server_host: 127.0.0.1
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 192.168.0.11
    - ::1
homeassistant:
  internal_url: http://192.168.0.11:8123
  external_url: !secret HA_URL
  time_zone: "Europe/London" 
  # time_zone: "Etc/GMT" # For google calendar authentication
  latitude: !secret LATITUDE
  longitude: !secret LONGITUDE

light:
  - platform: flux_led
    automatic_add: true
    devices:
      192.168.0.19:
        name: Bedroom Light Strip
  - platform: group
    name: Bedroom Lights
    entities:
      - light.bedroom_wall_light
      - light.bedroom_colours
  # - platform: mqtt
  #   schema: json
  #   name: light Strip
  #   state_topic: "lights/strip"
  #   command_topic: "lights/strip/set"
  #   json_attributes_topic: "lights/strip"
  #   # brightness: true
  #   # color_mode: true
  #   # supported_color_modes: ["rgb"]

logger:
  default: info
  logs:
    # homeassistant.components.alexa: debug
    homeassistant.components.sensor.fitbit: debug
    homeassistant.components.fitbit: debug
    custom_components.sensor.fitbit: debug
    custom_components.fitbit: debug

media_player:

mqtt:
  broker: 127.0.0.1
  port: 1883
  username: homeassistant
  password: !secret mqtt_pass
  discovery: true

recorder:
  db_url: !secret recorder_db_url

rest_command:
  todoist:
    method: post
    url: 'https://api.todoist.com/sync/v8/sync'
    payload: !secret todoist_api_payload
    content_type: 'application/x-www-form-urlencoded'

spotify:
  client_id: !secret spotify_client
  client_secret: !secret spotify_secret

tts:
  - platform: amazon_polly
    aws_access_key_id: !secret aws_access_key_ID
    aws_secret_access_key: !secret aws_secret_access_key
    region_name: 'eu-west-2'
    # text_type: ssml
    # voice: Joanna
    cache: True

wake_on_lan:

webostv:
  host: 192.168.0.15
  name: Living Room TV
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: !secret living_room_tv_mac
  customize:
    sources:
      -All 4
      -Amazon Prime Video
      -BBC iPlayer
      -Disney+
      -HDMI1
      -HDMI2
      -HDMI3
      -ITV Hub
      -My5
      -NOW TV
      -Netflix
      -Notifications
      -Plex
