- platform: fitbit
  clock_format: 24H
  monitored_resources:
    - "activities/calories"
    - "activities/caloriesBMR"
    - "activities/heart"
    - "activities/steps"
    - "devices/battery"
    - "sleep/awakeningsCount"
    - "sleep/efficiency"
    - "sleep/minutesAfterWakeup"
    - "sleep/minutesAsleep"
    - "sleep/minutesAwake"
    - "sleep/minutesToFallAsleep"
    - "sleep/startTime"
    - "sleep/timeInBed"

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: processor_use
    - type: last_boot