mysqldump -uuser -ppass --single-transaction --routines --triggers --all-databases > backup_db.sql
mysqldump --all-databases -uroot -p"$MYSQL_ROOT_PASSWORD"' > /some/path/on/your/host/all-databases.sql
