appdaemon:
  latitude: 0
  longitude: 0
  elevation: 30
  time_zone: Europe/London
  plugins:
    HASS:
      type: hass
      ha_url: http://192.168.0.11:8123
      token: !secret HA_TOKEN
    MQTT:
      type: mqtt
      namespace: mqtt
      client_host: 192.168.0.11
      client_port: 1883
      client_id: AD
      client_user: !secret MQTT_USER
      client_password: !secret MQTT_PASS
http:
  url: http://192.168.0.11:5050
admin:
api:
hadashboard:
# logs:
#   main_log:
#     filename: /conf/logs/appdaemon.log
#   access_log:
#     filename: /conf/logs/access.log
#   error_log:
#     filename: /conf/logs/error.log
#   diag_log:
#     filename: /conf/logs/diag.log
#     log_generations: 5
#     log_size: 1024
#     format: "{asctime} {levelname:<8} {appname:<10}: {message}"
#   test_log:
#     name: TestLog
#     filename: /conf/logs/test.log
logs:
  main_log:
    format: "{asctime} {levelname:<8} {appname:<10}: {message}"
  access_log:
    format: "{asctime} {levelname:<8} {appname:<10}: {message}"
  error_log:
    format: "{asctime} {levelname:<8} {appname:<10}: {message}"
  diag_log:
    format: "{asctime} {levelname:<8} {appname:<10}: {message}"
  # std:
  #   name: std
  #   format: "{asctime} {levelname:<8} {appname:<10}: {message}"