- id: '1632689360186'
  alias: Turn on light at night
  description: ''
  trigger:
  - platform: state
    entity_id: person.jim
    to: home
  - platform: numeric_state
    entity_id: sun.sun
    below: '8'
    attribute: elevation
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: '4'
  condition:
  - condition: state
    entity_id: person.jim
    state: home
  - condition: numeric_state
    entity_id: sun.sun
    attribute: elevation
    value_template: "{% if is_state(\"weather.jarvis\", \"sunny\") -%}\n  {{state_attr('sun.sun',
      'elevation') | float + 4}}\n{%- else -%}\n  {{state_attr('sun.sun', 'elevation')
      | float}}\n{%- endif %}"
    below: '8'
  action:
  - service: light.turn_on
    data:
      transition: 300
      brightness_pct: 100
    target:
      device_id: 9929ef9114c2392508fbe32ed426f34b
  mode: single
- id: '1633980276683'
  alias: Turn off bedroom speakers at night
  description: ''
  trigger:
  - platform: time
    at: '21:45'
  condition: []
  action:
  - service: switch.turn_off
    target:
      device_id: bd2923d9813f4473247009fcbe2e0d74
  mode: single
- id: '1634021797071'
  alias: Change Alexa volume when speakers disconnect
  description: ''
  trigger:
  - platform: state
    entity_id: switch.living_room_speakers
    to: 'Off'
  condition: []
  action:
  - service: media_player.volume_set
    target:
      entity_id: media_player.living_room_speaker
    data:
      volume_level: 0.4
  mode: single
- id: '1634022011502'
  alias: Turn on lights before waking
  description: ''
  trigger:
  - platform: time
    at: 06:30
  condition:
  - condition: state
    entity_id: person.jim
    state: Home
  action:
  - service: light.turn_on
    target:
      entity_id: light.bedroom_light_strip
    data:
      brightness_pct: 1
  - service: light.turn_on
    target:
      entity_id: light.bedroom_light_strip
    data:
      transition: 300
      brightness_pct: 100
  mode: single
- id: '1634026003029'
  alias: Turn off lights when bright
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    above: '10'
  condition:
  - condition: state
    entity_id: person.jim
    state: Home
  action:
  - service: light.turn_off
    target:
      entity_id: light.living_room_light
  mode: single
- id: '1639251416969'
  alias: Update Lightstrip speed when input is changed
  description: ''
  trigger:
  - platform: state
    entity_id: input_number.lightstrip_speed
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: LightStrip/in
      payload: ?{{ states.input_number.lightstrip_speed.state | int }}
  mode: single
- alias: Backup Home Assistant every night at 3 AM
  trigger:
    platform: time
    at: 03:00:00
  action:
    alias: Create backup now
    service: backup.create
  id: 00cdc3d4476d4facb65e619acc7eb01f
- id: '1664628058692'
  alias: Toggle bedroom light
  description: ''
  trigger:
  - platform: device
    domain: tasmota
    device_id: f565f4b376db10ab416fca6d541d1aec
    type: button_short_press
    subtype: button_1
    discovery_id: 40F520FBA0A4_button_1_SINGLE
  condition: []
  action:
  - type: toggle
    device_id: e48a62169a27e12cd5ee902c94e6ca36
    entity_id: light.bedroom_light
    domain: light
  mode: single
- id: '1664628593812'
  alias: Start bedtime on double button press
  description: ''
  trigger:
  - platform: device
    domain: tasmota
    device_id: f565f4b376db10ab416fca6d541d1aec
    type: button_double_press
    subtype: button_1
    discovery_id: 40F520FBA0A4_button_1_DOUBLE
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.bedroom_light_normal
    metadata: {}
  mode: single
- id: '1664635933647'
  alias: Turn on TV
  description: ''
  trigger:
  - platform: device
    device_id: ead1a929cfe977ccb9cac2aa51d5257b
    domain: webostv
    type: webostv.turn_on
  condition: []
  action:
  - service: wake_on_lan.send_magic_packet
    data:
      mac: B4:E6:2A:DE:42:F8
  mode: single
- id: '1665137072761'
  alias: Clickup webhook notification
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.clickup_webhook
    from: active
  condition:
  - condition: not
    conditions:
    - condition: state
      entity_id: sensor.clickup_webhook
      attribute: status
      state: active
  action:
  - service: notify.persistent_notification
    data:
      message: "Status: {{ state_attr('sensor.clickup_webhook', 'status') }} \nFail
        count: {{ state_attr('sensor.clickup_webhook', 'fail_count') }} \nDate suspended:
        {{ state_attr('sensor.clickup_webhook', 'date_suspended') }}"
      title: Clickup webhook
  mode: single
- id: '1665140075602'
  alias: Bedroom light triple press
  description: ''
  trigger:
  - platform: device
    domain: tasmota
    device_id: f565f4b376db10ab416fca6d541d1aec
    type: button_triple_press
    subtype: button_1
    discovery_id: 40F520FBA0A4_button_1_TRIPLE
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.bedtime
    metadata: {}
  mode: single
- id: '1665233594763'
  alias: Turn off lounge light when UV on
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.uv_lights
    to: 'on'
  condition: []
  action:
  - type: turn_off
    device_id: 22a560bbf56d16bfe4bc698ff7f1f4c6
    entity_id: light.lounge_light
    domain: light
  mode: single
- id: '1667252662452'
  alias: Set All Lights
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: group.set
    data:
      object_id: all_lights
      entities: '{{ states.light | rejectattr(''entity_id'',''eq'',''light.all_lights'')
        | map(attribute=''entity_id'') | list }}

        '
  - service: group.set
    data:
      object_id: inside_lights
      entities: '{{ states.light | rejectattr(''entity_id'', ''search'', (''outside''))
        | map(attribute=''entity_id'') | list }}

        '
  mode: single
- id: '1668066460553'
  alias: Control Freak Art
  description: ''
  trigger:
  - device_id: 7d15519274a37a2d2b9b1fdc9cd9f629
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: button
  condition: []
  action:
  - service: media_player.volume_set
    data:
      volume_level: 0.42
    target:
      entity_id: media_player.lounge
  - service: notify.alexa_media
    data:
      target: media_player.lounge
      data:
        type: tts
      message: <speak><audio src='https://jimbroze-jarvis.s3.eu-west-1.amazonaws.com/control.mp3'/></speak>
  - service: media_player.volume_set
    data:
      volume_level: 0.33
    target:
      entity_id: media_player.lounge
  mode: single
