- platform: fitbit
  # clock_format: 24H
  # unit_system: en_GB
  monitored_resources:
    - "activities/calories"
    - "activities/caloriesBMR"
    - "activities/heart"
    - "activities/steps"
    - "devices/battery"
    - "sleep/awakeningsCount"
    - "sleep/efficiency"
    - "sleep/minutesAfterWakeup"
    - "sleep/minutesAsleep"
    - "sleep/minutesAwake"
    - "sleep/minutesToFallAsleep"
    - "sleep/startTime"
    - "sleep/timeInBed"
  # # scan_interval: 30

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: processor_use
    - type: processor_temperature
    - type: last_boot

- platform: rest
  name: Todo List
  method: GET
  resource: 'https://api.todoist.com/sync/v8/projects/get_data'
  params:
    token: !secret TODOIST_TOKEN
    project_id: !secret todoist_next_actions_id
  value_template: '{{value_json[''project''][''id'']}}'
  json_attributes:
    - items
  scan_interval: 30

- platform: rest
  name: Shopping List
  method: GET
  resource: 'https://api.todoist.com/sync/v8/projects/get_data'
  params:
    token: !secret TODOIST_TOKEN
    project_id: !secret todoist_shopping_id
  value_template: '{{value_json[''project''][''id'']}}'
  json_attributes:
    - items
  scan_interval: 30

- platform: rest
  name: Clickup Webhook
  resource: 'https://api.clickup.com/api/v2/team/2193273/webhook'
  method: GET
  headers:
    Authorization: !secret CLICKUP_TOKEN
  value_template: "{{ value_json['webhooks'][0]['health']['status'] }}"
  json_attributes_path: "$.webhooks.[0].health"
  json_attributes:
    - status
    - fail_count
    - date_suspended