# log:
#   module: log
#   class: Log

# notifications:
#   module: notifications
#   class: Notifications
#   types:
#     Danger:
#       Urgency: Both
#       # Notification: Phone (Default)
#       Banner: True
#       Response: Required
#     Warning:
#       Urgency: Immediate
#       # Notification: Phone (Default)
#       Banner: True
#       Response: Optional
#     Question:
#       Urgency: Queued
#       # Notification: Alexa (Default)
#       Banner: False
#       Response: Required
#     Info (No response):
#       Urgency: Queued
#       # Notification: Alexa (Default)
#       Banner: False
#       Response: None
#     Reminder:
#       Urgency: If_Home
#       # Notification: Alexa (Default)
#       Banner: True
#       Response: None
#   Default_destinations:
#     immediate: Phone???
#     queued: media_player.living_room_speaker
#     both: Phone???
#     if_home: media_player.living_room_speaker

# notifications_listener:
#   module: notifications
#   class: NotificationListener

sound:
  module: sound
  class: Sound

server_fan:
  module: gpio
  class: ServerFan
  pin: 5
  fanBoolean: input_boolean.jarvis_fan
  tempSensor: sensor.processor_temperature
  high_temp: 55
  delta: 10
