name: Push - AppDaemon

on:
  push:
    branches:
      - 'appdaemon**'

  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ../../../../
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - run: git pull origin ${{ steps.extract_branch.outputs.branch }}
