name: Push - HomeAssistant

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    # container: homeassistant/home-assistant:latest
    steps:
      # - run: hass --script check_config -c .
      - uses: actions/checkout@v2
      - run: mv secrets.yaml.tmpl secrets.yaml
      - uses: kpucynski/action-ha-config-check@v0.1.0
        with:
          ha_version: "latest"
        # env:
        #   HASS_EXTRA_ARGS: "-f -s -i"

  # test-master-branch:
  #   runs-on: self-hosted
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: '14'
  #     - run: npm install -g bats
  #     - run: bats -v
