name: Push - HomeAssistant

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: homeassistant/home-assistant:latest
    steps:
      - run: hass --script check_config -c .


  # test-master-branch:
  #   runs-on: self-hosted
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: '14'
  #     - run: npm install -g bats
  #     - run: bats -v
