name: Release - Test, Build & Redeploy

on:
  push:
    branches:
      - "release-*"
    # Change to some sort of tag on main branch
    tags:
      - release*

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mv homeassistant/secrets.yaml.tmpl homeassistant/secrets.yaml && mv homeassistant/SERVICE_ACCOUNT.JSON.tmpl homeassistant/SERVICE_ACCOUNT.JSON
      - uses: kpucynski/action-ha-config-check@v0.1.0
        with:
          ha_version: "latest"
        env:
          CONFIG_PATH: ./homeassistant
        # env:
        #   HASS_EXTRA_ARGS: "-f -s -i"

  deploy:
    runs-on: self-hosted
    needs: [test]
    defaults:
      run:
        working-directory: ../../../../Docker
    steps:
      - run: git pull origin main
        working-directory: ../../../../
      - run: docker-compose stop
      - run: docker-compose build --pull
      - run: docker-compose pull
      - run: docker-compose up -d
