name: Release - Test, Build & Redeploy

on:
  push:
    branches:
      - 'release-*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: homeassistant/home-assistant:latest
    steps:
#        - uses: actions/checkout@v2
#       - uses: docker://homeassistant/home-assistant:latest
#         with:
#           entrypoint: hass --script check_config -c .
      - run: hass --script check_config -c .

  deploy:
    name: Deploy docker containers
    runs-on: self-hosted
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      - name: Stop Containers
        working-directory: Docker
        run: docker-compose stop
      - name: Build Images
        working-directory: Docker
        run: docker-compose build --pull
      - name: Start Containers
        working-directory: Docker
        run: docker-compose up
