name: Release - Test, Build & Redeploy

on:
  push:
    branches:
      - 'release-*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mv secrets.yaml.tmpl secrets.yaml && mv SERVICE_ACCOUNT.JSON.tmpl SERVICE_ACCOUNT.JSON
      - uses: kpucynski/action-ha-config-check@v0.1.0
        with:
          ha_version: "latest"
        # env:
        #   HASS_EXTRA_ARGS: "-f -s -i"

  deploy:
    runs-on: self-hosted
    needs: [test]
    defaults:
      run:
        working-directory: ../../../../Docker
    steps:
      - run: git pull
        working-directory: ../../../../
      - run: docker-compose stop
      - run: docker-compose build --pull
      - run: docker-compose up -d
